### PR TITLE
Add Makes

### PR DESCRIPTION
**Pull request by kamadorueda**

### CODE REVIEW

**Comment by kamadorueda** [comment]
Your review would be very appreciated guys

@Mic92 @zimbatm @ryantm

**Comment by Mic92** [comment]
I would leave the selection to @zimbatm

**Comment by zimbatm** [comment]
Can this be reduced to one entry? Makes looks pretty cool by the way.

**Comment by kamadorueda** [comment]
@zimbatm done! I added Makes only

I wanted to add both projects (Makes and Fluid Attacks) as both are built with Nix, the latter is an example of enterprise Nix usage

**Comment by zimbatm** [comment]
Hopefully, visitors can follow from one project to the other. There are a lot of things built with nix out there nowadays so we have to balance the real estate a bit.

**Pull request merged**
